### ISSUE TITLE
Getting error on arm64

### ISSUE THREAD

**Issue by abirabedinkhan** [pieroproietti/penguins-eggs-legacy#359]
When I installed the package it gave me the same error. Now I'm Trying to use it and also giving me the same error.
```
saplaos@BongoPC:~/Downloads$ eggs
/usr/lib/penguins-eggs/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/command.js:41
            delete this.globalFlags?.json;
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/penguins-eggs/node_modules/.pnpm/@oclif+core@1.26.2/node_modules/@oclif/core/lib/index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
```
                                 saplaos@BongoPC
                                 ---------------
      █ █ █ █ █ █ █ █ █ █ █      OS: Armbian (22.05.0-trunk) aarch64
     ███████████████████████     Host: Tanix TX6
   ▄▄██                   ██▄▄   Kernel: 5.15.27-station
   ▄▄██    ███████████    ██▄▄   Uptime: 9 hours, 58 mins
   ▄▄██   ██         ██   ██▄▄   Packages: 1526 (dpkg)
   ▄▄██   ██         ██   ██▄▄   Shell: bash 5.1.4
   ▄▄██   ██         ██   ██▄▄   Resolution: 1920x1080
   ▄▄██   █████████████   ██▄▄   Terminal: /dev/pts/0
   ▄▄██   ██         ██   ██▄▄   CPU: (4) @ 1.704GHz
   ▄▄██   ██         ██   ██▄▄   Memory: 569MiB / 1984MiB
   ▄▄██   ██         ██   ██▄▄
   ▄▄██                   ██▄▄
     ███████████████████████
      █ █ █ █ █ █ █ █ █ █ █
```

**Comment by pieroproietti** [comment]
That version? I made the last version 9.7.3 using node20, perhaps this Is the problem? Try 9.7.2 and tell me the results.

**Comment by abirabedinkhan** [comment]
Thanks for your assistance I change the version to node v20.12.2
Here my detail what I did ->
```
~$ sudo apt remove eggs && sudo apt autoremove
~$ curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash - 
~$ sudo apt-get install -y nodejs
~$ sudo apt install eggs
```

Then it started working
```
saplaos@BongoPC:~/Downloads/shrink-backup$ eggs
Perri's Brewery edition: remaster your system and distribuite it

VERSION
  penguins-eggs/9.7.3 linux-arm64 node-v20.12.2

USAGE
  $ eggs [COMMAND]

TOPICS
  export    export deb/docs/iso to the destination host
  tools     clean system log, apt, etc
  wardrobe  get warorobe

COMMANDS
  adapt         adapt monitor resolution for VM only
  analyze       analyze for syncto
  autocomplete  display autocomplete installation instructions
  calamares     configure calamares or install or configure it
  config        Configure and install prerequisites deb packages to run it
  cuckoo        PXE start with proxy-dhcp
  dad           ask help from daddy - TUI configuration helper
  help          Display help for eggs.
  install       krill: the CLI system installer - the egg became a penguin!
  kill          kill the eggs/free the nest
  krill         krill: the CLI system installer - the egg became a penguin!
  mom           ask help from mommy - TUI helper
  produce       produce a live image from your system whithout your data
  status        informations about eggs status
  syncfrom      restore users and user data from a LUKS volumes
  syncto        Save users and users' data ENCRYPTED
  update        update the Penguins' eggs tool
  version
```
